The entry point of the program was marked as `async`.

Erroneous code example:

```compile_fail,E0752
async fn main() -> Result<i32, ()> { // error!
    Ok(1)
}
```

`fn main()` or the specified start function is not allowed to be `async`. You
might be seeing this error because your async runtime library is not set up
correctly. To fix it, don't declare the entry point as `async`:

```
fn main() -> Result<i32, ()> { // ok!
    Ok(1)
}
```
