error: called `.iter().count()` on a `slice`
  --> $DIR/iter_count.rs:43:6
   |
LL |     &vec[..].iter().count();
   |      ^^^^^^^^^^^^^^^^^^^^^^ help: try: `vec[..].len()`
   |
   = note: `-D clippy::iter-count` implied by `-D warnings`

error: called `.iter().count()` on a `Vec`
  --> $DIR/iter_count.rs:44:5
   |
LL |     vec.iter().count();
   |     ^^^^^^^^^^^^^^^^^^ help: try: `vec.len()`

error: called `.iter().count()` on a `slice`
  --> $DIR/iter_count.rs:45:5
   |
LL |     boxed_slice.iter().count();
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `boxed_slice.len()`

error: called `.iter().count()` on a `VecDeque`
  --> $DIR/iter_count.rs:46:5
   |
LL |     vec_deque.iter().count();
   |     ^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `vec_deque.len()`

error: called `.iter().count()` on a `std::iter::Iterator`
  --> $DIR/iter_count.rs:47:5
   |
LL |     hash_set.iter().count();
   |     ^^^^^^^^^^^^^^^^^^^^^^^ help: try: `hash_set.len()`

error: called `.iter_mut().count()` on a `Vec`
  --> $DIR/iter_count.rs:49:5
   |
LL |     vec.iter_mut().count();
   |     ^^^^^^^^^^^^^^^^^^^^^^ help: try: `vec.len()`

error: called `.iter_mut().count()` on a `slice`
  --> $DIR/iter_count.rs:50:6
   |
LL |     &vec[..].iter_mut().count();
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `vec[..].len()`

error: called `.iter_mut().count()` on a `VecDeque`
  --> $DIR/iter_count.rs:51:5
   |
LL |     vec_deque.iter_mut().count();
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `vec_deque.len()`

error: called `.into_iter().count()` on a `slice`
  --> $DIR/iter_count.rs:53:6
   |
LL |     &vec[..].into_iter().count();
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `vec[..].len()`

error: called `.into_iter().count()` on a `Vec`
  --> $DIR/iter_count.rs:54:5
   |
LL |     vec.into_iter().count();
   |     ^^^^^^^^^^^^^^^^^^^^^^^ help: try: `vec.len()`

error: called `.into_iter().count()` on a `VecDeque`
  --> $DIR/iter_count.rs:55:5
   |
LL |     vec_deque.into_iter().count();
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `vec_deque.len()`

error: aborting due to 11 previous errors

