error: confusing error return, consider using `return Err(err)`
  --> $DIR/try_err.rs:7:5
   |
LL |     Err(err)?;
   |     ^^^^^^^^^ help: try this: `return Err(err)`
   |
note: lint level defined here
  --> $DIR/try_err.rs:1:9
   |
LL | #![deny(clippy::try_err)]
   |         ^^^^^^^^^^^^^^^

error: confusing error return, consider using `return Err(err.into())`
  --> $DIR/try_err.rs:14:5
   |
LL |     Err(err)?;
   |     ^^^^^^^^^ help: try this: `return Err(err.into())`

error: confusing error return, consider using `return Err(err)`
  --> $DIR/try_err.rs:31:13
   |
LL |             Err(err)?;
   |             ^^^^^^^^^ help: try this: `return Err(err)`

error: confusing error return, consider using `return Err(err.into())`
  --> $DIR/try_err.rs:46:13
   |
LL |             Err(err)?;
   |             ^^^^^^^^^ help: try this: `return Err(err.into())`

error: aborting due to 4 previous errors

