// run-fail
// error-pattern:panicked at 'assertion failed: false'

fn main() {
    assert!(false);
}
